### ISSUE TITLE
Upgrade from 2.15 to 2.20 causes TempData to be cleared, and massive slowdowns in MVC app

### ISSUE THREAD

**Issue by geirsagberg** [RickStrahl/Westwind.ApplicationConfiguration#3]
After upgrading from 2.15 to 2.20, I notice massive slowdowns in my MVC app. Also, when I set a value in TempData in a Controller Action, the value is no longer there when rendering the View. Any idea why this is happening?

I am using the following config:

```
    public class MyConfig : AppConfiguration
    {
        public string EmailFromAddress { get; private set; }
        public string EmailDefaultAddress { get; private set; }

        protected override IConfigurationProvider OnCreateDefaultProvider(string sectionName, object configData)
        {
            var provider = new ConfigurationFileConfigurationProvider<MyConfig>
            {
                ConfigurationSection = null // Use appSettings instead of configSection in web.config.
            };
            return provider;
        }
    }
```

**Comment by geirsagberg** [comment]
Could it be that the appSettings in web.config are modified/touched when the config is read, causing an app pool recycle?

**Comment by RickStrahl** [comment]
Not sure what would be causing a slow down like this compared to the old version. Nothing's really changed in the way the configuration provider loads the configuration in this version - the only thing changed is serialization with extended types (which don't apply in this simple file).

Can you profile to see where the slowdown is occurring? If TempData is getting wiped, then it sure looks like the AppDomain is cycling, which should only be caused if the configuration values are updated and Write() is called.

How are you instantiating the configuration? You should be using App.Configuration (ie. a static that's global in scope) - otherwise the config object reads the settings each time and might end up writing those values as well if they don't exist or can't be written due to permissions.

FWIW, I'm not seeing any slowdowns on my apps, but I'll take a look tomorrow to see whether the config is being touched on every read - it shouldn't be unless you're writing or you've added new properties/values.

**Comment by geirsagberg** [comment]
I am instantiating the configuration with NInject in singleton scope:
`Bind<IMyConfig>().To<MyConfig>().InSingletonScope().OnActivation(hc => hc.Initialize());`

After testing, I have found that the appSettings are being wiped out somehow; I have settings like:

```
<appSettings>
    <add key="EmailFromAddress" value="<my email>" />
    <add key="EmailDefaultAddress" value="<my email>" />
</appSettings>
```

After running the app, they have been set to:

```
<appSettings>
    <add key="EmailFromAddress" value="" />
    <add key="EmailDefaultAddress" value="" />
</appSettings>
```

**Comment by geirsagberg** [comment]
I find the problem is in these lines from ConfigurationFileConfigrationProvider.cs:141:

```
            configManager = string.IsNullOrEmpty(ConfigurationSection)
                ? ConfigurationManager.GetSection("AppSettings") as NameValueCollection
                : ConfigurationManager.GetSection(ConfigurationSection) as NameValueCollection;


            if (configManager == null)
            {
                Write(config);
                return true;
            }
```

The section "AppSettings" is not found, so the provider writes the settings to web.config.
If I change to the following:

```
            configManager = string.IsNullOrEmpty(ConfigurationSection)
                ? ConfigurationManager.AppSettings
                : ConfigurationManager.GetSection(ConfigurationSection) as NameValueCollection;
```

then everything works as expected.

**Comment by RickStrahl** [comment]
Thanks Geir. I'll double check this and get it moved in, but it looks your change would work fine. That code did indeed get changed at some point and there might be a couple of other places where this is is happening.

**Comment by RickStrahl** [comment]
Fixed per suggestion and double checked that it doesn't cause problem with other operations (writes and custom file reads still use a section name via XML DOM ops). Added a test to check this scenario by writing a value and reloading the provider to check for the new value rather than overwritten default values as before.
