### ISSUE TITLE
XmlFileConfigurationProvider don't serialize TimeSpan. Alternatives? 

### ISSUE THREAD

**Issue by Edddy** [RickStrahl/Westwind.ApplicationConfiguration#9]
I'm using some `TimeSpan`s but they are serialized to null, like: 

```
     <HoraDesde />
```

**Comment by RickStrahl** [comment]
More info please. What are you serializing? Config file or raw XML. For config it won't work if there's no type converter - nor would I recommend storing complex data like this in a config file.

**Comment by Edddy** [comment]
It's pretty simple. 

```
public TimeSpan HoraDesde  { get; set; }
HoraDesde = new TimeSpan(8,0,0);
```

Get's serialized as 

```
 <HoraDesde />
```

I'm using the Json provider now, It works fine with it.

**Comment by RickStrahl** [comment]
Yes the issue is that the XmlSerializer doesn't serialize TimeSpan values natively. 

Here's a StackOverflow Issue that describes the problem and a not so pretty workaround.
http://stackoverflow.com/questions/637933/net-how-to-serialize-a-timespan-to-xml

There's nothing we can do on the library end generically that I can think of that would make this work generically. 

I think for configuration purposes using something other than a timespan is probably a better choice anyway. Using Minutes, Seconds, Milliseconds or something along those lines probably makes for a better configuration setting than a timespan, since it's much more difficult to edit manually in the XML document.

**Comment by Edddy** [comment]
No problem, I'm using the JsonProvider now, works perfectly.
